### ISSUE TITLE
好像没有起到作用

### ISSUE THREAD

**Issue by shark-lajiao** [CaoMeiYouRen/vite-plugin-fast-cdn-import#2]
![截图 2022-11-29 10-57-32](https://user-images.githubusercontent.com/86769380/204427779-a3ce6621-ba87-4fc8-ad35-28fb68543364.png)

**Comment by shark-lajiao** [comment]
![image](https://user-images.githubusercontent.com/86769380/204427857-a889cbe5-209b-4aca-ac4e-39cf2649fa15.png)

**Comment by CaoMeiYouRen** [comment]
`cdnUrls` 填错了，应该是 `https://cdn.jsdelivr.net/npm/:name@:version/:path`。
然后是目前只设计了 css 部分的加载，js 部分没有考虑。
使用了本插件的话项目内就不用在引一次 css 了

**Comment by CaoMeiYouRen** [comment]
> ![截图 2022-11-29 10-57-32](https://user-images.githubusercontent.com/86769380/204427779-a3ce6621-ba87-4fc8-ad35-28fb68543364.png)

还有就是 ，cdnUrls 只填一个的话是无法竞速的，也就无法根据竞速结果来选择加载哪个 CDN 源，至少得两个以上才能有效果。

**Comment by shark-lajiao** [comment]
好的，我明白了，谢谢您
